services:
  frontend:
    build:
     context: ./frontend
     dockerfile: Dockerfile
  backend:
    build:
     context: ./backend
     dockerfile: Dockerfile
    depends_on:
      - mysql
  mysql:
    image: bitnami/mysql:5.7.43
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql@2025
      MYSQL_DATABASE: test
    volumes:
      - ./mysql:/bitnami/mysql/data
      - ./mysql-initdb:/docker-entrypoint-initdb.d
  proxy:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend