services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - myapp-network

  db:
    image: mysql:8.0
    container_name: mysql-container
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: mysql@2025
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - myapp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=mysql", "--user=root", "--password=mysql@2025"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    build:
      context: ./backend
    container_name: backend-container
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=mysql@2025
      - DB_NAME=test
    ports:
      - "8800:8800"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge